Initial reproducible setup
verloop/k8s-aws pull request #1
Opened 2016-12-18 04:54 UTC by ofpiyush

To try this, create a cluster following the instructions in the README.

Should I create a .sh file/cli client which does these things for you?

If you have a free aws account, it should work.

The docker image should be enough to perform basic k8s tasks.

2016-12-19 06:51 UTC, avinassh commented
> Should I create a .sh file/cli client which does these things for you?

Yes, please.

2016-12-19 06:51 UTC, avinassh requested changes

2016-12-19 06:51 UTC, avinassh commented on README.md
> +$ kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/monitoring-standalone/v1.2.0.yaml
Its better to pull this file from tagged version. Latest release seems to be v1.4.3:

    kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/v1.4.3/addons/monitoring-standalone/v1.2.0.yaml

2016-12-19 08:04 UTC, ofpiyush commented on README.md
> +$ kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/monitoring-standalone/v1.2.0.yaml
👍

2016-12-19 10:01 UTC, ofpiyush commented
@sgaurav @avinassh updated readme and moved some things to scripts, please check.

2016-12-20 11:06 UTC, avinassh approved these changes

2016-12-20 11:07 UTC, merged